---
- name: Launch QNG Amana Privnet Node
  hosts: poa_nodes
  become: yes
  vars:
    qng_binary_path: /usr/local/bin/qng
    data_dir: /home/poa-node2/.qng/data/privnet
    config_file: /home/poa-node2/qng_privnet/node2/amana-privnet-launcher/config.toml
    password_file: /home/poa-node2/qng_privnet/node2/amana-privnet-launcher/password.txt
    mining_address: "SeRg5WhrcEKBGd6YsA5Um1wpQkYuKei3p1"  # Example Base58 address
  tasks:
    - name: Copy QNG binary
      copy:
        src: "{{ qng_binary_path }}"
        dest: /usr/local/bin/qng
        mode: '0755'

    - name: Create data directory
      file:
        path: "{{ data_dir }}"
        state: directory
        mode: '0755'

    - name: Copy config.toml
      copy:
        src: "{{ config_file }}"
        dest: /home/poa-node2/.qng/qng.conf

    - name: Launch QNG Node with Amana Privnet
      shell: |
        nohup qng \
          --configfile /home/poa-node2/.qng/qng.conf \
          --privnet \
          --acctmode \
          --generate \
          --amana \
          --miningaddr {{ mining_address }} \
          --datadir {{ data_dir }} &
      args:
        executable: /bin/bash
