- name: Launch QNG Amana Privnet Node
  hosts: poa_nodes
  become: yes
  vars:
    qng_binary_path: /usr/local/bin/qng
    data_dir: /home/{{ ansible_user }}/.qng/data/privnet
    config_file: /home/{{ ansible_user }}/qng_privnet/{{ inventory_hostname }}/amana-privnet-launcher/config.toml
    password_file: /home/{{ ansible_user }}/qng_privnet/{{ inventory_hostname }}/amana-privnet-launcher/password.txt
    mining_address: "SeRg5WhrcEKBGd6YsA5Um1wpQkYuKei3p1"  # Example Base58 address
  tasks:
    - name: Ensure QNG binary is installed
      copy:
        src: "{{ qng_binary_path }}"
        dest: /usr/local/bin/qng
        mode: '0755'

    - name: Create data directory
      file:
        path: "{{ data_dir }}"
        state: directory
        mode: '0755'

    - name: Copy config.toml to correct location
      copy:
        src: "{{ config_file }}"
        dest: /home/{{ ansible_user }}/.qng/qng.conf

    - name: Launch QNG Node with Amana Privnet
      shell: |
        nohup qng \
          --configfile /home/{{ ansible_user }}/.qng/qng.conf \
          --privnet \
          --acctmode \
          --generate \
          --amana \
          --modules=admin,eth,net,web3 \
          --miningaddr {{ mining_address }} \
          --datadir {{ data_dir }} > /home/{{ ansible_user }}/nohup.out 2>&1 &
      args:
        executable: /bin/bash
